### PR TITLE
«‎Interact: beacon v2»‎

### PR DESCRIPTION
**Pull request by ungarson**

### CODE REVIEW

**Comment by m-kus** [comment]
Related https://github.com/airgap-it/beacon-sdk/issues/120

**Comment by ungarson** [comment]
Related https://github.com/airgap-it/beacon-sdk/issues/132

**Comment by ungarson** [comment]
Related https://github.com/airgap-it/beacon-sdk/issues/132

**Comment by AndreasGassmann** [comment]
We have just released beacon-sdk `2.2.0-beta.0`. It doesn't contain any changes in the logic, but it does include some big changes in the UI part. You can give it a try on https://walletbeacon.io. If you have any feedback, please let us know. It will probably be 1 or 2 weeks before we release 2.2.0 final because we want to get as much feedback as possible.

BTW, there is now also a darkmode. A full changelog can be found here: https://github.com/airgap-it/beacon-sdk/blob/feat/toast-improvements-details/docs/CHANGELOG.md

**Comment by ungarson** [comment]
@AndreasGassmann thanks, good job really!! 🙏🏻

**Comment by RomanSerikov** [comment]
[Interact: beacon v2](https://trello.com/c/sqrLRXow/749-interact-beacon-v2)

**Pull request merged**
